config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :incomings
  end

    resources :products do
      resources :outgoings
    end

  resources :outgoings

  resources :incomings

  resources :products

  devise_for :users
  root to: 'products#index'

end

app/models/incoming.rb
class Incoming < ActiveRecord::Base
  belongs_to :product
end

app/models/outgoing.rb
class Outgoing < ActiveRecord::Base
  belongs_to  :product
  validate :check_stock


  def check_stock
    @product = Product.find_by(product_id)
    @product.total_stock
    if @product.total_stock <= quantity
      errors.add(:quantity,'out of limit stock ' )
    end
  end
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :outgoings
  has_many :incomings
  belongs_to :incoming

  def total_incoming_quantity
   self.incomings.sum(:quantity)
  end

  def total_outgoing_quantity
    self.outgoings.sum(:quantity)
  end
  def total_stock
    total_incoming_quantity - total_outgoing_quantity
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/incomings_controller.rb
class IncomingsController < ApplicationController
  before_action :set_incoming, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @incomings = Incoming.all
    respond_with(@incomings)
  end

  def show
    respond_with(@incoming)
  end

  def new
    @incoming = Incoming.new
    respond_with(@incoming)
  end

  def edit
  end

  def create
    @incoming = Incoming.new(incoming_params)
    @incoming.save
    respond_with(@incoming)
  end

  def update
    @incoming.update(incoming_params)
    respond_with(@incoming)
  end

  def destroy
    @incoming.destroy
    respond_with(@incoming)
  end

  private
    def set_incoming
      @incoming = Incoming.find(params[:id])
    end

    def incoming_params
      params.require(:incoming).permit(:quantity, :date, :product_id, :product_name, :name)
    end
end

app/controllers/outgoings_controller.rb
class OutgoingsController < ApplicationController
  before_action :set_outgoing, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @outgoings = Outgoing.all
    respond_with(@outgoings)
  end

  def show
    respond_with(@outgoing)
  end

  def new
    @outgoing = Outgoing.new
    respond_with(@outgoing)
  end

  def edit

  end

  def create
    @outgoing = Outgoing.new(outgoing_params)
    @outgoing.save
    respond_with(@outgoing)
  end

  def update
    @outgoing.update(outgoing_params)
    respond_with(@outgoing)
  end

  def destroy
    @outgoing.destroy
    respond_with(@outgoing)
  end

  private
    def set_outgoing
      @outgoing = Outgoing.find(params[:id])
    end

    def outgoing_params
      params.require(:outgoing).permit(:quantity, :date, :product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ProductPdf.new(@products)
        send_data pdf.render, filename: "product_#{@products}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def show

  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :incoming_quantity, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incomings_helper.rb
module IncomingsHelper
end

app/helpers/outgoings_helper.rb
module OutgoingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<p>
  welcome
</p>

app/views/incomings/_form.html.erb
<%= form_for(@incoming) do |f| %>
  <% if @incoming.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incoming.errors.count, "error") %> prohibited this incoming from being saved:</h2>

      <ul>
      <% @incoming.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Barang_Masuk %><br>
    <%= f.select("product_id", Product.all.collect {|p| [ p.name,p.id ] }, { include_blank: true }) %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomings/edit.html.erb
<h1>Editing incoming</h1>

<%= render 'form' %>

<%= link_to 'Show', @incoming %> |
<%= link_to 'Back', incomings_path %>

app/views/incomings/index.html.erb
<h1>Listing incomings</h1>

<table class ="table table-striped">
  <thead>
    <tr>
      <th>Product Id</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomings.each do |incoming| %>
      <tr>
        <td><%= incoming.product.id %></td>
        <td><%= incoming.product.name%></td>
        <td><%= incoming.quantity %></td>
        <td><%= incoming.date %></td>
        <td><%= link_to 'Show', incoming %></td>
        <td><%= link_to 'Edit', edit_incoming_path(incoming) %></td>
        <td><%= link_to 'Destroy', incoming, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incoming', new_incoming_path %>

app/views/incomings/new.html.erb
<h1>New incoming</h1>

<%= render 'form' %>

<%= link_to 'Back', incomings_path %>

app/views/incomings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @incoming.quantity %>
</p>

<p>
  <strong>Date:</strong>
  <%= @incoming.date %>
</p>

<%= link_to 'Edit', edit_incoming_path(@incoming) %> |
<%= link_to 'Back', incomings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inven</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"  style="background-color:#2c3e50;">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to "Inventory", root_url, class: "navbar-brand" %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                  <li><%= link_to current_user.email%></li>
                  <li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>
                  <li><%= link_to "All Products",root_path%></li>
                  <li><%= link_to "Transaksi Masuk",incomings_path%></li>
                  <li><%= link_to "Transaksi Keluar",outgoings_path%></li>
                <% else %>
                  <li><%= link_to "Sign In", user_session_path %></li>
                  <li><%= link_to "Register", new_user_registration_path %></li>
                <% end %>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>

  <!-- Page Content -->
  <div class="container">

      <div class="row">
          <div class="col-lg-12">
            <% flash.each do |a,b| %>
              <div class="alert alert-succes"> <%= b %> </div>
              <% end %>
            <%= yield %>
          </div>
      </div>
  </div>
  <!-- /.container -->
  <style> body{padding-top:70px;}</style>
</body>
</html>

app/views/outgoings/_form.html.erb
<%= form_for(@outgoing) do |f| %>
  <% if @outgoing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outgoing.errors.count, "error") %> prohibited this outgoing from being saved:</h2>

      <ul>
      <% @outgoing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Outgoing %><br>
    <%= f.select("product_id", Product.all.collect{|p| [p.name,p.id ]}, { include_blank: true}) %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outgoings/edit.html.erb
<h1>Editing outgoing</h1>

<%= render 'form' %>

<%= link_to 'Show', @outgoing %> |
<%= link_to 'Back', outgoings_path %>

app/views/outgoings/index.html.erb
<h1>Listing outgoings</h1>

<table class ="table table-striped" >
  <thead>
    <tr>
      <th>Product ID</th>
      <th>Product Name</th>
      <th>Quantity</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outgoings.each do |outgoing| %>
      <tr>
        <td><%= outgoing.product_id %></td>
        <td><%= outgoing.product.name %></td>
        <td><%= outgoing.quantity %></td>
        <td><%= outgoing.date %></td>
        <td><%= link_to 'Show', outgoing %></td>
        <td><%= link_to 'Edit', edit_outgoing_path(outgoing) %></td>
        <td><%= link_to 'Destroy', outgoing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outgoing', new_outgoing_path %>

app/views/outgoings/new.html.erb
<h1>New outgoing</h1>

<%= render 'form' %>

<%= link_to 'Back', outgoings_path %>

app/views/outgoings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @outgoing.quantity %>
</p>

<p>
  <strong>Date:</strong>
  <%= @outgoing.date %>
</p>

<%= link_to 'Edit', edit_outgoing_path(@outgoing) %> |
<%= link_to 'Back', outgoings_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table class ="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Available Stock </th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.total_stock%></td>
        <td>Rp.<%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <p>
    <%= link_to "Printable Product", products_path(@products, format: "pdf") %>
  </p>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>